# custom variables
title:              HexChat
url:                https://hexchat.github.io
dl_url:             https://dl.hexchat.net
version:            2.10.1

# permalinks
permalink:          /news/:title.html

exclude:            ["README.md"]

markdown:           kramdown
gems:
    - jekyll-sitemap
